name: vacuum_persistent
version: 1.0.0
author: see AUTHORS
description: Efficient persistent data structures for Dart
homepage: https://github.com/vacuumlabs/persistent
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  args: '>=0.9.0 <0.10.0'
  benchmark_harness: any
  enumerators: '>=0.5.0 <0.6.0'
  http: '>=0.9.0 <0.10.0'
  unittest: '>=0.9.0 <0.10.0'
dependencies:
  quiver: '>=0.18.0 <1.0.0'
